### ISSUE TITLE
HI 大大 請問遊戲設定相關

### ISSUE THREAD

**Issue by jimmy8399** [aNyMoRe0505/cs2-mm-server-picker#3]
請問遊戲內的延遲設定 有甚麼建議嗎? 中華500/500  設定那個到底有用嗎?
延遲限制那個掉包率甚麼的 他有兩個設定

**Comment by aNyMoRe0505** [comment]
那個設定和這個 app 無關, 我記得無限制是最好的吧 (?, 最低延遲我是 40

我的情況是就算設定40, 但因為香港會是 30 ~ 100 在飄, 最後還是會被分配到香港, 所以才有這個程式把香港的 route ban 掉
