### ISSUE TITLE
我選了日本兩個還是優先會排到香港伺服器

### ISSUE THREAD

**Issue by Siaomo** [aNyMoRe0505/cs2-mm-server-picker#4]
請問能不能直接把香港ban掉不要排到這個伺服器一直掉封包又卡又隨時爆炸PING

**Comment by aNyMoRe0505** [comment]
@Siaomo 
防火牆 -> 進階設定 -> 輸出規則 有出現 `cs2-mm-server-picker` 嗎?

**Comment by Siaomo** [comment]
![螢幕擷取畫面 2023-10-30 202651](https://github.com/aNyMoRe0505/cs2-mm-server-picker/assets/78332860/48f056f2-3583-4169-b08a-116f61c89382)
我現在連打快12小時cs2腦袋有點ㄎ一ㄤ了 我這樣設定對我不確定

**Comment by aNyMoRe0505** [comment]
你用的版本是哪個? `CS2` 是自己設定的嗎?
是的話把 CS2 和 cs2-mm-server-picker 刪除
重新勾日本伺服器然後按執行試試看

**Comment by aNyMoRe0505** [comment]
我剛剛測試還是可以用, 應該是你自己新增 CS2 的關係
就都刪除然後重新用程式執行吧, 成功後 update ping 其他伺服器的數值應該會是 NaN

**Comment by Siaomo** [comment]
好謝謝 我試試看 謝謝很早就給星星了 超好用

**Comment by aNyMoRe0505** [comment]
@Siaomo 問題有解決嗎?

**Comment by Siaomo** [comment]
有看起來現在使用狀況看起來是正常的我再繼續多測試 因為講完把那個刪掉我才打了兩場
已經筋疲力盡了 明天會開始繼續連打10小時看看 應該是沒問題了感謝有我會在告知
